import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { fakeUserData } from "./api/index";
import { useDispatch } from "react-redux";
import { addUser } from "@/src/service/redux/slices/userSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const dispatch = useDispatch()

  const userDetails = (name) => {
    console.log(name);
    dispatch(addUser(name))
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
      <button onClick={() => userDetails(fakeUserData())}>Add user</button>
      <ul>
        <li></li>
      </ul>
    </>
  );
}
